#ifndef PINDEFINITIONS_H
#define PINDEFINITIONS_H


// #define PIN_BL    GPIO_NUM_12 // TDI JTAG PIN ALSO USED AS BACKLIGHT

// #define PIN_LED      GPIO_NUM_2  // LED AND BOOT MODE
#define PIN_LED   GPIO_NUM_15 // TDO JTAG PIN ALSO USED AS LED

#define PIN_PWR_DET  GPIO_NUM_25 // CHECK IF HAS EXTERNAL POWER  
#define PIN_BAT_STAT GPIO_NUM_26 // ANALOG BATTEY PERCENT 
#define PIN_CS_SD    GPIO_NUM_27 // SD CHIP SELECT

#define PIN_CHG_DET  GPIO_NUM_35 // HIGH OR LOW WHEN BATTERY CHARGING

// PIN definitions for display
#define PIN_DISP_BUSY GPIO_NUM_4
#define PIN_DSIP_CS   GPIO_NUM_5
#define PIN_DISP_RST  GPIO_NUM_16
#define PIN_DISP_DC   GPIO_NUM_17

// PIN definitions for input
#define BT_INPUT_0 GPIO_NUM_36 // SENSOR_VP PIN 4
#define BT_INPUT_1 GPIO_NUM_39 // SENSOR_VN PIN 5
#define BT_INPUT_2 GPIO_NUM_34 // PIN 6 INPUT ONLY

#endif