#include "ButtonActions.h"

/**
 * Function to extract hold bit from the joystick signal
 * 
 * @param input generated by SwithInputHandler
 * @param held  held bit. Will be modified as resylt of function execution
 * 
 * @returns input without B00010000 bit
 */
uint8_t controlDirection(uint8_t input, bool &held)
{
    // Check of hold bit is set
    held = input & B00010000;

    // return input without hold bit
    return input & ~B00010000;;
}